In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import datasist as ds
sns.set(rc={'figure.figsize':[10,10]},font_scale=1.2)

In [2]:
df = pd.read_csv('train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
df.drop(['Cabin'],axis=1,inplace=True)

In [9]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [10]:
from datasist.structdata import detect_outliers

In [15]:
num_col= df.select_dtypes(include=['number']).columns
num_col

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [17]:
for col in num_col:
    
    out_indices= detect_outliers(df,0,[col])
    print(f'column: {col}====>{len(out_indices)}outliers')
    df.loc[out_indices,col]=np.nan

column: PassengerId====>0outliers
column: Survived====>0outliers
column: Pclass====>0outliers
column: Age====>0outliers
column: SibSp====>46outliers
column: Parch====>213outliers
column: Fare====>116outliers


In [19]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp           46
Parch          213
Ticket           0
Fare           116
Embarked         2
dtype: int64

In [34]:
missing_col  = df.isna().sum().sort_values(ascending=False)[:1]
missing_col

Embarked    2
dtype: int64

In [35]:
from sklearn.impute import KNNImputer

In [37]:
imputer= KNNImputer()

In [39]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(7), object(4)
memory usage: 76.7+ KB


In [53]:
df= pd.get_dummies(df,  columns=['Name',  'Ticket'],drop_first=True)
df

PassengerId  Survived  Pclass        Age  SibSp  Parch       Fare  \
0            1.0       0.0     3.0  22.000000    1.0    0.0   7.250000   
1            2.0       1.0     1.0  38.000000    1.0    0.0  17.822091   
2            3.0       1.0     3.0  26.000000    0.0    0.0   7.925000   
3            4.0       1.0     1.0  35.000000    1.0    0.0  53.100000   
4            5.0       0.0     3.0  35.000000    0.0    0.0   8.050000   
..           ...       ...     ...        ...    ...    ...        ...   
886        887.0       0.0     2.0  27.000000    0.0    0.0  13.000000   
887        888.0       1.0     1.0  19.000000    0.0    0.0  30.000000   
888        889.0       0.0     3.0  29.699118    1.0    0.0  23.450000   
889        890.0       1.0     1.0  26.000000    0.0    0.0  30.000000   
890        891.0       0.0     3.0  32.000000    0.0    0.0   7.750000   

     Sex_male  Embarked_Q  Embarked_S  ...  Ticket_STON/O2. 3101290  \
0           1           0           1  ...                        0   
1           0           0           0  ...                        0   
2           0           0           1  ...                        0   
3           0           0           1  ...                        0   
4           1           0           1  ...                        0   
..        ...         ...         ...  ...                      ...   
886         1           0           1  ...                        0   
887         0           0           1  ...                        0   
888         0           0           1  ...                        0   
889         1           0           0  ...                        0   
890         1           1           0  ...                        0   

     Ticket_SW/PP 751  Ticket_W./C. 14258  Ticket_W./C. 14263  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   
..                ...                 ...                 ...   
886                 0                   0                   0   
887                 0                   0                   0   
888                 0                   0                   0   
889                 0                   0                   0   
890                 0                   0                   0   

     Ticket_W./C. 6607  Ticket_W./C. 6608  Ticket_W./C. 6609  \
0                    0                  0                  0   
1                    0                  0                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   
..                 ...                ...                ...   
886                  0                  0                  0   
887                  0                  0                  0   
888                  1                  0                  0   
889                  0                  0                  0   
890                  0                  0                  0   

     Ticket_W.E.P. 5734  Ticket_W/C 14208  Ticket_WE/P 5735  
0                     0                 0                 0  
1                     0                 0                 0  
2                     0                 0                 0  
3                     0                 0                 0  
4                     0                 0                 0  
..                  ...               ...               ...  
886                   0                 0                 0  
887                   0                 0                 0  
888                   0                 0                 0  
889                   0                 0                 0  
890                   0        

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [56]:
y.value_counts()

0.0    549
1.0    342
Name: Survived, dtype: int64

In [57]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [58]:
y_train.value_counts()

0.0    439
1.0    273
Name: Survived, dtype: int64

In [59]:
from imblearn.under_sampling import RandomUnderSampler

In [60]:
sampler = RandomUnderSampler()

In [61]:
x_train,y_train = sampler.fit_resample(x_train,y_train)

In [62]:
y_train.value_counts()

0.0    273
1.0    273
Name: Survived, dtype: int64

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler= StandardScaler()

In [65]:
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [66]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [67]:
models= {
    'LogisticRegression':LogisticRegression(),
    'KNeighborsClassifier':KNeighborsClassifier(),
    'SVC':SVC(),
    'GaussianNB':GaussianNB(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'XGBClassifier':XGBClassifier()
}


In [69]:
for name,model in models.items():
    print(f'Training Model {name}\n-----------')
    model.fit(x_train,y_train)
    y_pred= model.predict(x_test)
    print(f'Training Accuarcy:{accuracy_score(y_train,model.predict(x_train))}')
    print(f'Testing Accuarcy:{accuracy_score(y_test,y_pred)}')
    print(f'Testing Confusion Matrix: \n{confusion_matrix(y_test,y_pred)}')
    print(f'Testing Recall: {recall_score(y_test,y_pred)}')
    print(f'Testing precision: {precision_score(y_test,y_pred)}')
    print(f'Testing F-1: {f1_score(y_test,y_pred)}')

Training Model LogisticRegression
-----------
Training Accuarcy:1.0
Testing Accuarcy:0.7597765363128491
Testing Confusion Matrix: 
[[80 30]
 [13 56]]
Testing Recall: 0.8115942028985508
Testing precision: 0.6511627906976745
Testing F-1: 0.7225806451612903
Training Model KNeighborsClassifier
-----------
Training Accuarcy:0.5439560439560439
Testing Accuarcy:0.4022346368715084
Testing Confusion Matrix: 
[[  3 107]
 [  0  69]]
Testing Recall: 1.0
Testing precision: 0.39204545454545453
Testing F-1: 0.563265306122449
Training Model SVC
-----------
Training Accuarcy:1.0
Testing Accuarcy:0.4022346368715084
Testing Confusion Matrix: 
[[  3 107]
 [  0  69]]
Testing Recall: 1.0
Testing precision: 0.39204545454545453
Testing F-1: 0.563265306122449
Training Model GaussianNB
-----------
Training Accuarcy:1.0
Testing Accuarcy:0.441340782122905
Testing Confusion Matrix: 
[[11 99]
 [ 1 68]]
Testing Recall: 0.9855072463768116
Testing precision: 0.40718562874251496
Testing F-1: 0.576271186440678
Training 

C:\anaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


Training Accuarcy:1.0
Testing Accuarcy:0.7150837988826816
Testing Confusion Matrix: 
[[81 29]
 [22 47]]
Testing Recall: 0.6811594202898551
Testing precision: 0.618421052631579
Testing F-1: 0.6482758620689655
